# Site settings
title: Origamijs.com
email: rapha850@gmail.com
description: Official website origami.js
baseurl: ""
url: http://origamijs.com
domain: origamijs.com

# Build settings
markdown: kramdown
